spring:
#  templates?? ? html????
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
# Marid DB??
  datasource:
    url: jdbc:mariadb://localhost:3308/cloneinstagram
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
# ?????
  servlet:
    multipart:
      # ?? ?? ???
      max-file-size: 5MB
      # ?? ?? ???
      max-request-size: 30MB
      location: D:/instagramUpload

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 620099338582-2qqffr1f9cpdb3b9uc5u3182g1mgn3aq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          facebook:
            client-id: 386408816154911
            client-secret: 6ac071e2f7f6d4f8d907f4c1f136db91
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: 5bde7f187546c23a7eaff34ee83ace50
            client-secret: 0Mx6CTQ26sZGgpzNEQC81GJW9z27Jq1K
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: cg6Me_544AENt8lMRy13
            client-secret: UBdZe0ONwE
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
# xml??? DB??? ??
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.koreait.cloneinstagram

server:
  port: 8090